### ISSUE TITLE
TODO/FIXME Count 25

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/credential-handler-polyfill#16]
- [ ] TODO: only expose certain APIs when appropriate
       Commit: (adb2688) Add polyfill load to happen in parallel w/ relying party site load.
       File:  [index.js:48](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/index.js#L48)
       Dave Longley commented 2 years ago

  - [ ] TODO: Add section explaining how CHAPI interacts with existing complementary
       Commit: (faad08a) Change link to demo wallet, extract motivation and background to docs.
       File:  [docs/motivation-and-background.md:36](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/docs/motivation-and-background.md#L36)
       Dmitri Zagidulin commented 4 months ago

  - [ ] TODO: Explain the importance of polyfills for driving innovation and standards
       Commit: (faad08a) Change link to demo wallet, extract motivation and background to docs.
       File:  [docs/motivation-and-background.md:30](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/docs/motivation-and-background.md#L30)
       Dmitri Zagidulin commented 4 months ago

  - [ ] TODO: Discuss creating and receiving WebCredential instances
       Commit: (6f971a1) Add WebCredential section.
       File:  [README.md:105](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/README.md#L105)
       Dmitri Zagidulin commented 10 months ago

  - [ ] webcredential)
       Commit: (6f971a1) Add WebCredential section.
       File:  [README.md:94](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/README.md#L94)
       Dmitri Zagidulin commented 10 months ago

  - [ ] TODO: Update to something more useful
       Commit: (6f971a1) Add WebCredential section.
       File:  [README.md:80](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/README.md#L80)
       Dmitri Zagidulin commented 10 months ago

  - [ ] TODO: validate result
       Commit: (58a76ab) Return `WebCredential`.
       File:  [CredentialsContainer.js:60](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialsContainer.js#L60)
       Dave Longley commented 3 years ago

  - [ ] TODO: validate credential
       Commit: (58a76ab) Return `WebCredential`.
       File:  [CredentialsContainer.js:43](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialsContainer.js#L43)
       Dave Longley commented 3 years ago

  - [ ] TODO: validate handlerResponse
       Commit: (0f35e98) Add core files.
       File:  [CredentialStoreEvent.js:49](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialStoreEvent.js#L49)
       Dave Longley commented 3 years ago

  - [ ] TODO: throw exception if `_promise` is already set
       Commit: (0f35e98) Add core files.
       File:  [CredentialStoreEvent.js:47](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialStoreEvent.js#L47)
       Dave Longley commented 3 years ago

  - [ ] TODO: note that `appWindow.handle` is not a ServiceWorker
       Commit: (0f35e98) Add core files.
       File:  [CredentialStoreEvent.js:38](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialStoreEvent.js#L38)
       Dave Longley commented 3 years ago

  - [ ] TODO: ensure `url` is to the same origin
       Commit: (0f35e98) Add core files.
       File:  [CredentialStoreEvent.js:33](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialStoreEvent.js#L33)
       Dave Longley commented 3 years ago

  - [ ] TODO: disallow more than one call
       Commit: (0f35e98) Add core files.
       File:  [CredentialStoreEvent.js:31](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialStoreEvent.js#L31)
       Dave Longley commented 3 years ago

  - [ ] TODO: may not be able to even extend `Event` here; could produce "incorrect"
       Commit: (0f35e98) Add core files.
       File:  [CredentialStoreEvent.js:13](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialStoreEvent.js#L13)
       Dave Longley commented 3 years ago

  - [ ] TODO: validate handlerResponse
       Commit: (0f35e98) Add core files.
       File:  [CredentialRequestEvent.js:51](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialRequestEvent.js#L51)
       Dave Longley commented 3 years ago

  - [ ] TODO: throw exception if `_promise` is already set
       Commit: (0f35e98) Add core files.
       File:  [CredentialRequestEvent.js:49](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialRequestEvent.js#L49)
       Dave Longley commented 3 years ago

  - [ ] TODO: note that `appWindow.handle` is not a ServiceWorker
       Commit: (0f35e98) Add core files.
       File:  [CredentialRequestEvent.js:40](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialRequestEvent.js#L40)
       Dave Longley commented 3 years ago

  - [ ] TODO: ensure `url` is to the same origin
       Commit: (0f35e98) Add core files.
       File:  [CredentialRequestEvent.js:33](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialRequestEvent.js#L33)
       Dave Longley commented 3 years ago

  - [ ] TODO: disallow more than one call
       Commit: (0f35e98) Add core files.
       File:  [CredentialRequestEvent.js:31](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialRequestEvent.js#L31)
       Dave Longley commented 3 years ago

  - [ ] TODO: may not be able to even extend `Event` here; could produce "incorrect"
       Commit: (0f35e98) Add core files.
       File:  [CredentialRequestEvent.js:13](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialRequestEvent.js#L13)
       Dave Longley commented 3 years ago

  - [ ] TODO: `reject` as an error and fail `.set`?
       Commit: (f68f506) Fix typo and add TODO.
       File:  [CredentialHints.js:51](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialHints.js#L51)
       Dave Longley commented 3 years ago

  - [ ] TODO: validate credential hint
       Commit: (7f9bbed) Ensure icons are prefetched.
       File:  [CredentialHints.js:23](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialHints.js#L23)
       Dave Longley commented 3 years ago

  - [ ] TODO: validate credentialStoreEvent
       Commit: (0f35e98) Add core files.
       File:  [CredentialHandlerService.js:24](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialHandlerService.js#L24)
       Dave Longley commented 3 years ago

  - [ ] TODO: validate credentialRequestEvent
       Commit: (0f35e98) Add core files.
       File:  [CredentialHandlerService.js:17](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialHandlerService.js#L17)
       Dave Longley commented 3 years ago

  - [ ] TODO: may need to do `this.hide()` after this promise resolves
       Commit: (0f35e98) Add core files.
       File:  [CredentialHandler.js:23](https://github.com/digitalbazaar/credential-handler-polyfill.git/blob/master/CredentialHandler.js#L23)
       Dave Longley commented 3 years ago
